# Generated by Django 2.2 on 2019-04-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('connection_id', models.UUIDField()),
                ('invite_url', models.URLField()),
            ],
        ),
    ]
