# Generated by Django 2.2.4 on 2019-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_verification', '0002_auto_20190415_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField()),
                ('state', models.TextField()),
            ],
        ),
    ]
