kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}-build-template
  creationTimestamp: null
objects:
  - kind: NetworkSecurityPolicy
    apiVersion: security.devops.gov.bc.ca/v1alpha1
    metadata:
      name: ${ENV_NAME}-pods-to-external-network
      labels:
        name: pods-to-external-network
        env: ${ENV_NAME}
    spec:
      description: Allow the builds to access the internet. This only needs to be specified once per environment.
      source:
        - - $namespace=${NAMESPACE_NAME}-${ENV_NAME}
      destination:
        - - ext:network=any
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${APP_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${APP_NAME}
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ${SOURCE_IMAGE_KIND}
            name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          env:
            - name: PIP_INDEX_URL
              value: ${PIP_INDEX_URL}
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
    value: email-verification-service
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together.
    required: true
    value: email-verification-service
  - name: ENV_NAME
    displayName: Environment Name
    description: Environment name.  For the build environment this will typically be 'tools'
    required: true
    value: tools
  - name: NAMESPACE_NAME
    displayName: NameSpace name
    description: name of the project namespace
    required: true
    value: a99fd4
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
    value: https://github.com/bcgov/indy-email-verification.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: false
    value: src
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: The 'kind' (type) of the  source image; typically ImageStreamTag,
      or DockerImage.
    required: true
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
    value: registry.access.redhat.com/rhscl/python-36-rhel7
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: latest
  - name: PIP_INDEX_URL
    displayName: Custom PyPi Index URL
    description: The custom PyPi index URL
    value: ''
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
