kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}${SUFFIX}-deployment-template
  annotations:
    description: Deployment template for a django server connected to a PostGreSQL
      database.
    tags: django
    iconClass: icon-python
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${NAME}-allow-ingress
      labels:
        name: ${NAME}-allow-ingress
        app: ${APP_NAME}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      description: |
        Allow traffic from routes into the ${ROLE} container(s).
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector:
        matchLabels:
          role: ${ROLE}
          app: ${APP_NAME}
          env: ${TAG_NAME}
      policyTypes:
        - Ingress
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    stringData:
      oidc-rp-provider-endpoint: ${OIDC_RP_PROVIDER_ENDPOINT}
      oidc-rp-client-id: ${OIDC_RP_CLIENT_ID}
      oidc-rp-client-secret: ${OIDC_RP_CLIENT_SECRET}
      oidc-rp-scopes: ${OIDC_RP_SCOPES}
      vc-authn-pres-req-conf-id: ${VC_AUTHN_PRES_REQ_CONF_ID}
      oidc-claims-required: ${OIDC_CLAIMS_REQUIRED}
    type: Opaque
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: ${NAME}${SUFFIX}
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APP_NAME}${SUFFIX}
        name: ${NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
        certbot-managed: ${CERTBOT_MANAGED_ROUTE}
      name: ${NAME}${SUFFIX}
    spec:
      host: ${APPLICATION_DOMAIN}
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}${SUFFIX}
        weight: 100
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
      annotations:
        description: Defines how to deploy the application server
      labels:
        name: ${NAME}${SUFFIX}
        app: ${APP_NAME}${SUFFIX}
        app-group: ${APP_GROUP}
        role: ${ROLE}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${NAME}:${TAG_NAME}
        - type: ConfigChange
      replicas: 1
      selector:
        name: ${NAME}${SUFFIX}
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            name: ${NAME}${SUFFIX}
            app: ${APP_NAME}${SUFFIX}
            app-group: ${APP_GROUP}
            role: ${ROLE}
            env: ${TAG_NAME}
        spec:
          containers:
            - name: ${NAME}${SUFFIX}
              image: ' '
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 5
                periodSeconds: 30
                initialDelaySeconds: 3
                timeoutSeconds: 40
                httpGet:
                  path: /
                  port: 8080
              livenessProbe:
                failureThreshold: 5
                periodSeconds: 60
                initialDelaySeconds: 30
                timeoutSeconds: 40
                httpGet:
                  path: /
                  port: 8080
              env:
                - name: APP_FILE
                  value: ${APP_FILE}
                - name: APP_CONFIG
                  value: ${APP_CONFIG}
                - name: APP_MODULE
                  value: ${APP_MODULE}
                - name: DJANGO_SECRET_KEY
                  value: ${DJANGO_SECRET_KEY}
                - name: DJANGO_DEBUG
                  value: ${DJANGO_DEBUG}
                - name: VERIFIER_NAME
                  value: ${VERIFIER_NAME}
                - name: OIDC_RP_PROVIDER_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: oidc-rp-provider-endpoint
                - name: OIDC_RP_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: oidc-rp-client-id
                - name: OIDC_RP_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: oidc-rp-client-secret
                - name: OIDC_RP_SCOPES
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: oidc-rp-scopes
                - name: VC_AUTHN_PRES_REQ_CONF_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: vc-authn-pres-req-conf-id
                - name: OIDC_CLAIMS_REQUIRED
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: oidc-claims-required
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to
      the server instance.
    required: true
    value: email-verification-demo
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: email-verification-service
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: email-verification-demo
  - name: SUFFIX
    displayName: Suffix
    description: A name suffix used for all objects
    required: false
    value: ''
  - name: ROLE
    displayName: Role
    description: The role of this service within the application - used for Network Policies
    required: true
    value: email-verification-demo
  - description: The exposed hostname that will route to the service, e.g., myappname.pathfinder.gov.bc.ca, if left blank a value will be defaulted.
    displayName: Application Hostname
    name: APPLICATION_DOMAIN
    value: verified-email-authentication-dev.apps.silver.devops.gov.bc.ca
  - name: CERTBOT_MANAGED_ROUTE
    displayName: Certbot Managed Route
    description: Flag indicating whether the routes certificates are managed by CertBot.
    required: true
    value: 'false'
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: bztwou-tools
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    value: dev
    required: true
  - name: APP_FILE
    displayName: Application File
    description: Used to run the application from a Python script. This should be
      a path to a Python file (defaults to app.py unless set to null) that will be
      passed to the Python interpreter to start the application (optional).
    required: false
    value: ''
  - name: APP_CONFIG
    displayName: Application Configuration File Path
    description: Relative path to Gunicorn configuration file (optional).
    required: false
    value: ''
  - name: APP_MODULE
    displayName: Application Module
    description: The python module for application startup.
    required: false
    value: ''
  - name: DJANGO_SECRET_KEY
    displayName: Django Secret Key
    description: Set this to a long random string.
    generate: expression
    from: '[\w]{50}'
  - name: DJANGO_DEBUG
    displayName: Django Debug
    description: If Django is in debug mode
    required: true
    value: 'False'
  - name: VERIFIER_NAME
    displayName: Verifier Name
    description: Verifier Name
    required: true
    value: Verified Email Authentication
  - name: OIDC_RP_PROVIDER_ENDPOINT
    displayName: OIDC RP Provider Endpoint
    description: OIDC RP Provider Endpoint
    required: true
    value: ''
  - name: OIDC_RP_CLIENT_ID
    displayName: OIDC RP Client Id
    description: OIDC RP Client Id
    required: true
    value: ''
  - name: OIDC_RP_CLIENT_SECRET
    displayName: OIDC RP Client Secret
    description: OIDC RP Client Secret
    required: true
    value: ''
  - name: OIDC_RP_SCOPES
    displayName: OIDC RP Scopes
    description: OIDC RP Scopes
    required: false
    value: openid profile vc_authn
  - name: VC_AUTHN_PRES_REQ_CONF_ID
    displayName: VC Authentication Presentation Request Configuration Id
    description: VC Authentication Presentation Request Configuration Id
    required: true
    value: ''
  - name: OIDC_CLAIMS_REQUIRED
    displayName: OIDC Claims Required
    description: OIDC Claims Required
    required: true
    value: ''
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 10m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 300m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 10Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
